# Generated by Django 4.0.3 on 2022-03-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture_url',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
