# Generated by Django 4.0.3 on 2022-03-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lhl', '0002_member_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='picture_url',
            new_name='imgurl',
        ),
    ]
